# Generated by Django 2.1.7 on 2019-03-11 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_auto_20190311_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeModel',
        ),
    ]
