# Generated by Django 2.1.7 on 2019-03-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='enabled',
            new_name='show_suggestions',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='transparent',
            new_name='transparent_suggestions',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='alias_content_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='app_installed_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='app_uninstalled_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='navigationbar_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='overlay_color',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='statusbar_color',
        ),
    ]
