# Generated by Django 2.1.7 on 2019-03-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0008_auto_20190315_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='notes_color',
            field=models.TextField(default='#8BC34A'),
        ),
    ]
